import fs from 'fs';

// Read the current questions file
const filePath = 'src/data/matric2015SocialHistoryQuestions.ts';
let content = fs.readFileSync(filePath, 'utf-8');

// Answer key with correct answers (0=A, 1=B, 2=C, 3=D) and explanations
const answerKey = {
  1: { answer: 1, explanation: "The Oromo population movement in the 16th century was primarily driven by the need to find new pastures for their cattle, as they were pastoralist people. This is historically documented as the main push factor for their expansion." },
  2: { answer: 0, explanation: "Emperor Serse Dingil faced Turkish expansionism beyond the Mereb River in the 1570s. The Ottoman Empire was expanding its influence in the Red Sea region during this period." },
  3: { answer: 3, explanation: "Iyasu I earned the nickname 'Iyasu the Great' primarily for his restoration of Gondernine rule over south-western Ethiopia. He successfully campaigned to reassert imperial authority over lost territories." },
  4: { answer: 0, explanation: "The Ching (Qing) dynasty gained support from the Han ruling class by continuing Chinese administrative practices. This policy of adopting Chinese institutions helped legitimize their rule." },
  5: { answer: 3, explanation: "The fundamental source of conflict between Charles I and the English Short Parliament was the dispute over raising taxes to suppress the rebellion in Scotland. Parliament refused to grant funds without addressing grievances." },
  6: { answer: 1, explanation: "A dominant idea among Enlightenment thinkers was that humans can achieve progress through the application of reason. This belief in human rationality and progress was central to Enlightenment philosophy." },
  7: { answer: 3, explanation: "The Latin American revolutions in the early 19th century were inspired by ideas generated by Enlightenment thinkers, particularly concepts of liberty, equality, and popular sovereignty." },
  8: { answer: 3, explanation: "The common feature of the 1848 revolutions in Europe was that they ultimately failed because of divisions among the leadership on future goals. Despite initial successes, internal disagreements led to their collapse." },
  9: { answer: 3, explanation: "Mohammed Ali of Egypt was responsible for the end of the Funj Sultanate. He invaded and conquered the Funj kingdom in the 1820s, bringing it under Egyptian control." },
  10: { answer: 2, explanation: "Egypt's prosperity under the Mamluks was largely due to Egypt's participation in the trans-Saharan trade. This trade brought wealth from West African gold and other commodities." },
  11: { answer: 2, explanation: "The Mongols were responsible for invading India in the 14th century under Timur (Tamerlane) in 1398. This invasion had significant impact on the Delhi Sultanate." },
  12: { answer: 3, explanation: "Bilen is a Central Cushitic language. The other options (Gedeo, Burji, Beja) belong to different language families within the Cushitic or Afro-Asiatic groups." },
  13: { answer: 1, explanation: "The ancient state of Punt was located in Northeast Africa, likely in the area of modern-day Somalia, Eritrea, or Sudan. It was a trading partner of ancient Egypt." },
  14: { answer: 0, explanation: "The rise of the Zagwe Dynasty was facilitated by the popularity the Agaw gained because of the rock-hewn churches they built, particularly the famous churches of Lalibela." },
  15: { answer: 3, explanation: "Renaissance Humanism was characterized by an interest in everyday human conditions and secular matters, moving away from the purely religious focus of the medieval period." },
  16: { answer: 2, explanation: "The Solomonic rulers developed a prison system for male royal descendants, known as the 'mountain prisons,' to prevent succession disputes by isolating potential claimants." },
  17: { answer: 0, explanation: "A characteristic feature of the Muslim sultanates of Medieval Ethiopia was that their economy was mainly dependent on trade, particularly with the Red Sea and Indian Ocean trading networks." },
  18: { answer: 3, explanation: "The Kingdom of Kafa had developed an efficient system of defending its territory through its well-organized military and natural defensive advantages." },
  19: { answer: 2, explanation: "The main cause for the expansion of the Christian kingdom during the medieval period was the desire to expand its resource base, including acquiring new lands and economic resources." },
  20: { answer: 2, explanation: "The conflict between the Christian kingdom and the Sultanate of Adal intensified due to the establishment of the Turks along the Red Sea coast, which brought firearms and new military dynamics." },
  21: { answer: 2, explanation: "The gada institution declined among the Oromo of the Gibe region due to warfare and the rise of powerful war leaders, who established hereditary rule instead of the rotational gada system." },
  22: { answer: 2, explanation: "The route Jiren-Seka-Soddo-Aliya Amba was not a correct description of 19th century Ethiopian long-distance trade routes. The other routes were historically documented." },
  23: { answer: 1, explanation: "Giuseppe Garibaldi's role was to inspire and lead a popular uprising for Italian unification. He led the 'Expedition of the Thousand' that conquered the Kingdom of the Two Sicilies." },
  24: { answer: 3, explanation: "The Congress of Vienna created a German confederation led by Austria, which ultimately laid the groundwork for future German unification movements." },
  25: { answer: 0, explanation: "A major consequence of the American Civil War was the industrialization of the American economy. The war accelerated Northern industrial growth and transformed the economic landscape." },
  26: { answer: 2, explanation: "The spread of nationalism among the Slavic peoples of the Ottoman Empire contributed to the emergence of the 'Eastern Question' - the problem of how to deal with the declining Ottoman Empire." },
  27: { answer: 0, explanation: "Tewodros II came to power by defeating his opponents through military means. He rose through military campaigns against various regional lords and established his authority." },
  28: { answer: 1, explanation: "The Battle of Assam helped Kassa Mircha (later Emperor Yohannes IV) defeat a major rival and hence become emperor. This victory was a turning point in his rise to power." },
  29: { answer: 1, explanation: "Menelik used force for state societies but negotiation among non-state peoples. This differentiated approach allowed him to expand efficiently through different regions." },
  30: { answer: 0, explanation: "Article 17 of the Wuchale Treaty became a source of conflict because the Italian version stated that Ethiopia had agreed to become an Italian protectorate, which was not in the Amharic version." },
  31: { answer: 0, explanation: "Damot was a southern state that exercised extensive influence in areas south of the Abbay before the 14th century. It was a significant pre-Aksumite and early medieval kingdom." },
  32: { answer: 2, explanation: "A feature of European society during the 'Dark Ages' was the rise in the power of local rulers at the expense of kings and emperors, leading to feudal fragmentation." },
  33: { answer: 3, explanation: "Early capitalism in Europe featured the rise in importance of the bourgeoisie in economic and cultural life, marking a shift from feudal aristocratic dominance." },
  34: { answer: 2, explanation: "The cause of conflict between the Christian highland kingdom and Muslim sultanates was the desire to control the lucrative Zeila trade route, which was economically vital for both." },
  35: { answer: 0, explanation: "The adoption of aspects of the gada system by the Christian state was NOT a consequence of the Oromo movement. The other options (shift to agriculture, assimilation, loss of territory) were actual consequences." },
  36: { answer: 1, explanation: "The Jesuits failed because their attempt to convert Ethiopia to Catholicism led to widespread opposition by the population, resulting in revolt and the eventual abdication of Susenyos." },
  37: { answer: 0, explanation: "The Khoi (Khoikhoi) were cattle herders in southern Africa, while the San were hunter-gatherers. The Hausa and Swahili were West and East African groups respectively." },
  38: { answer: 3, explanation: "The second phase of the Trans-Atlantic slave trade was called 'Monopolistic slave trade' when European powers held official monopolies over the trade." },
  39: { answer: 2, explanation: "Industrial capitalism featured the replacement of human and animal labor by new inanimate sources of power, particularly steam power, which revolutionized production." },
  40: { answer: 2, explanation: "The fundamental cause of the American Civil War was opposition by the colonies to British policy on slavery, alongside economic and political tensions between North and South." },
  41: { answer: 0, explanation: "Modernization in Ethiopia under Menelik II failed mainly for lack of finance. The country lacked the resources needed for comprehensive modernization efforts." },
  42: { answer: 3, explanation: "Bismarck's system of alliances led to the establishment of two hostile military camps in Europe, which eventually contributed to the outbreak of World War I." },
  43: { answer: 0, explanation: "A consequence of the First World War was the establishment of British and French dominance in the Middle East through the mandate system created by the League of Nations." },
  44: { answer: 1, explanation: "The Russian working class supported the 1917 Revolution because living conditions of workers had worsened significantly due to war-related economic disruptions." },
  45: { answer: 2, explanation: "Italy undermined Ethiopian unity before the 1935 invasion by bribing Ethiopian officials to weaken the imperial government, using divide-and-conquer tactics." },
  46: { answer: 1, explanation: "Fascist rule was limited largely to urban centers because the countryside was a base for the resistance movement, making rural areas difficult to control." },
  47: { answer: 2, explanation: "The fundamental factor for WWII was the feeling of victimhood felt by Germans about the Versailles Treaty, which Hitler exploited to gain political support." },
  48: { answer: 3, explanation: "The immediate factor for WWII was the invasion of Poland by the German army on September 1, 1939, which led to Britain and France declaring war." },
  49: { answer: 2, explanation: "At the Tehran Conference of 1943, the idea of forming the UN received support from the great powers (Roosevelt, Churchill, and Stalin), paving the way for its creation." },
  50: { answer: 0, explanation: "Hungary was a member of the Warsaw Pact, the Soviet-led military alliance in Eastern Europe established in 1955 as a counterbalance to NATO." },
  51: { answer: 0, explanation: "A historian establishes the value of a source by carrying out a critical evaluation, assessing its authenticity, reliability, and relevance to the research question." },
  52: { answer: 2, explanation: "A limitation of Ethiopian historiography has been the heavy emphasis on political history rather than other kinds of history, such as social, economic, or cultural history." },
  53: { answer: 2, explanation: "Homo erectus is distinguished by being the first species to develop the technology of using fire, which was a major technological advancement in human evolution." },
  54: { answer: 1, explanation: "The Neolithic Revolution in Ethiopia has been reconstructed with artefacts from sites such as Gobedra and Lake Beseka, which provide archaeological evidence of early agriculture." },
  55: { answer: 2, explanation: "The theory of Oriental Despotism proposes that states emerged out of the necessity of organizing large-scale irrigation works, requiring centralized authority." },
  56: { answer: 3, explanation: "During the New Kingdom, Egypt expanded its empire to parts of Asia and Africa, including Syria-Palestine and Nubia, making it a major imperial power." },
  57: { answer: 1, explanation: "The Sumerians developed astronomy and mathematics, including the base-60 number system we still use for time and angles today." },
  58: { answer: 2, explanation: "Athenian democracy was characterized by the passage of laws through direct participation of citizens in the assembly, rather than through representatives." },
  59: { answer: 3, explanation: "During the early Middle Ages, the Catholic Church served as a center of culture and learning, preserving knowledge and providing education in monasteries and cathedral schools." },
  60: { answer: 1, explanation: "The Battle of Nihawand (642 CE) led to the end of the Persian Empire, marking the decisive victory of Muslim Arab forces over the Sassanid Persians." },
  61: { answer: 2, explanation: "Italy achieved unification in the 19th century through the spread of Italian nationalism throughout the Italian Peninsula, led by figures like Mazzini, Cavour, and Garibaldi." },
  62: { answer: 3, explanation: "The British used indirect rule through local chiefs while the French ruled directly themselves through appointed administrators, representing different colonial administrative philosophies." },
  63: { answer: 3, explanation: "Long distance trade helped consolidate states in the Gibe region by introducing new ideas and practices that legitimized the power of rulers and connected them to wider networks." },
  64: { answer: 1, explanation: "The major difference between Tewodros and Yohannes was that Tewodros centralized power in his hands while Yohannes did not achieve the same level of centralization." },
  65: { answer: 3, explanation: "The Ethiopians used the tactic of denying the Italians access to sources of water to eject them from Mekelle in January 1896, forcing their surrender." },
  66: { answer: 1, explanation: "The Shewan nobility opposed Lij Iyasu because he threatened their political position in the Empire, fearing loss of their traditional privileges and influence." },
  67: { answer: 3, explanation: "Lij Iyasu's initiative to abolish the system of identifying robbers and thieves was important in reforming the legal system, moving toward more modern judicial practices." },
  68: { answer: 0, explanation: "The main feature of the Diarchy in early 20th-century Ethiopia was rivalry between conservative and progressive groups in the ruling class, particularly between the Empress and the Regent." },
  69: { answer: 2, explanation: "The 1931 Constitution enabled autocratic rule by granting the Emperor the right to disband parliament at his own will, centralizing power in the monarch." },
  70: { answer: 3, explanation: "The Ashanti Empire succeeded in repulsing the British in 1876 because they had a well-organized army with effective military leadership and strategies." },
  71: { answer: 3, explanation: "The Indian National Congress adopted non-violence struggle methods under Gandhi's leadership, using civil disobedience and peaceful resistance against British rule." },
  72: { answer: 2, explanation: "A consequence of the First Arab-Israeli War was the emergence of a Palestinian Arab refugee problem, as hundreds of thousands of Palestinians fled or were expelled." },
  73: { answer: 3, explanation: "The USA intervened in Vietnam after the French defeat because of fear that Vietnamese victory would lead to the spread of communism across the region (the domino theory)." },
  74: { answer: 1, explanation: "The British helped Haile Selassie consolidate his powers after 1941 by training and equipping his army, which strengthened his control over the country." },
  75: { answer: 3, explanation: "The Chamber of Deputies became elective under the 1955 Constitution, representing a step toward constitutional monarchy and parliamentary representation." },
  76: { answer: 1, explanation: "The 1960 coup against Haile Selassie failed because it was not planned and led effectively, lacking proper coordination and popular support." },
  77: { answer: 2, explanation: "A consequence of the 1974 Ethiopian Revolution was the centralization of power under a new regime (the Derg), which overthrew the imperial system." },
  78: { answer: 0, explanation: "Marcus Garvey's pan-African movement advocated that blacks in the diaspora could achieve full independence only by returning to Africa, promoting the 'Back to Africa' movement." },
  79: { answer: 1, explanation: "The Mau Mau organized an armed struggle against the British in Kenya, using guerrilla warfare tactics to fight for land and independence." },
  80: { answer: 3, explanation: "The All-African People's Conference at Accra established the principle that African states should respect each other's territorial integrity, a key OAU principle." },
  81: { answer: 2, explanation: "Prehistory is the study of the period before the beginning of writing, encompassing all human history before written records were kept." },
  82: { answer: 1, explanation: "The theory of evolution states that humans are products of natural selection and adaptation, as proposed by Charles Darwin." },
  83: { answer: 1, explanation: "The Mesolithic age witnessed the shift from hunting and gathering to agriculture, serving as a transitional period between the Paleolithic and Neolithic ages." },
  84: { answer: 1, explanation: "The central point of the theocratic theory of state formation is that states were created by religious experts or through religious authority." },
  85: { answer: 0, explanation: "The construction of the pyramids demonstrates that the ancient Egyptians had made significant advances in engineering and architecture, requiring sophisticated mathematical knowledge." },
  86: { answer: 2, explanation: "Ancient Persia maintained administrative control through the introduction of an effective postal relay system, known as the Angarium, which facilitated rapid communication." },
  87: { answer: 3, explanation: "Punt was the earliest state in Ethiopia and the Horn, existing as a trading partner with ancient Egypt from at least the 3rd millennium BCE." },
  88: { answer: 1, explanation: "A major achievement of Muslim Arab civilization was the preservation of ancient Greek texts through translation, which were later reintroduced to Europe." },
  89: { answer: 2, explanation: "Cultural continuity between the Zagwe and Aksumite periods is shown by the important role Christianity enjoyed as the official religion of the state." },
  90: { answer: 1, explanation: "The Christian highland kingdom depended on mobile camps because they enabled rulers to control their empire more effectively than permanent capitals, allowing rapid response to threats." },
  91: { answer: 0, explanation: "A major cause of World War I was the rise of intense nationalism among European countries, which created tensions and rivalries between the great powers." },
  92: { answer: 2, explanation: "The military losses that Russia suffered in WWI were responsible for the outbreak of the 1917 Russian Revolution, as they discredited the Tsarist regime." },
  93: { answer: 0, explanation: "During the Italian occupation, there was expansion of road infrastructure as the Italians built roads to facilitate military control and economic exploitation." },
  94: { answer: 1, explanation: "WWII led to the reduction of Italian troops in Ethiopia, which encouraged the growth of the resistance movement (the Patriots/Arbegnoch)." },
  95: { answer: 2, explanation: "The UNO was established to resolve international conflicts peacefully, following the failure of the League of Nations to prevent World War II." },
  96: { answer: 1, explanation: "The anti-colonial movements in Algeria and Kenya both tried peaceful methods but resorted to armed resistance when peaceful approaches failed to achieve independence." },
  97: { answer: 2, explanation: "Independent African states established the OAU in 1963 because they wanted to establish an association independent of the Super Powers, promoting African unity and cooperation." },
  98: { answer: 2, explanation: "The Imperial Board of Telecommunications was rebuilt with US help in the post-liberation period, as part of modernization efforts supported by American aid." },
  99: { answer: 3, explanation: "The 1973-74 famine led to the loss of legitimacy for the Imperial Government, as it demonstrated the government's inability to address the suffering of its people." },
  100: { answer: 2, explanation: "The Derg Regime became unpopular because of using violence against opposition groups, including the Red Terror campaign that targeted political opponents." }
};

// Parse the content and update answers
let updatedContent = content;

for (let i = 1; i <= 100; i++) {
  const key = answerKey[i];
  if (!key) continue;
  
  // Replace correctAnswer: -1 with correctAnswer: X
  const pattern1 = new RegExp(`"id": "m2015-social-hist-${i}"[\\s\\S]*?"correctAnswer": -1`, 'g');
  const replacement1 = `"id": "m2015-social-hist-${i}",\n    "question": [\\s\\S]*?"correctAnswer": ${key.answer}`;
  
  // Update correctAnswer
  updatedContent = updatedContent.replace(
    new RegExp(`(\"id\": \"m2015-social-hist-${i}\"[\\s\\S]*?\"correctAnswer\": )-1`, 'g'),
    `$1${key.answer}`
  );
  
  // Update explanation
  updatedContent = updatedContent.replace(
    new RegExp(`(\"id\": \"m2015-social-hist-${i}\"[\\s\\S]*?\"explanation\": )\"\"`, 'g'),
    `$1"${key.explanation}"`
  );
}

// Clean up "Share Share This Question" from questions
updatedContent = updatedContent.replace(/Share Share This Question /g, '');

fs.writeFileSync(filePath, updatedContent);
console.log('Updated all 100 History 2015 questions with answers and explanations');
