export interface BookSubject {
  name: string;
  description: string;
  pages: string;
  size: string;
  image: string;
  pdf: string;
}

export interface BookGrade {
  grade: number;
  accent: string;
  description: string;
  subjects: BookSubject[];
}

export const booksByGrade: BookGrade[] = [
  {
    grade: 9,
    accent: "from-emerald-500 to-teal-500",
    description: "Foundation textbooks for lower secondary study with direct local PDF access.",
    subjects: [
      {
        name: "Amharic",
        description: "Official Grade 9 Amharic student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "175 pages",
        size: "1 MB",
        image: "/books/covers/grade-9-amharic.png",
        pdf: "/books/pdfs/grade-9-amharic.pdf",
      },
      {
        name: "Biology",
        description: "Official Grade 9 Biology student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "171 pages",
        size: "11 MB",
        image: "/books/covers/grade-9-biology.png",
        pdf: "/books/pdfs/grade-9-biology.pdf",
      },
      {
        name: "Chemistry",
        description: "Official Grade 9 Chemistry student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "183 pages",
        size: "7 MB",
        image: "/books/covers/grade-9-chemistry.png",
        pdf: "/books/pdfs/grade-9-chemistry.pdf",
      },
      {
        name: "Citizenship Education",
        description: "Official Grade 9 Citizenship Education student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "173 pages",
        size: "7 MB",
        image: "/books/covers/grade-9-citizenship-education.png",
        pdf: "/books/pdfs/grade-9-citizenship-education.pdf",
      },
      {
        name: "Economics",
        description: "Official Grade 9 Economics student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "119 pages",
        size: "4 MB",
        image: "/books/covers/grade-9-economics.png",
        pdf: "/books/pdfs/grade-9-economics.pdf",
      },
      {
        name: "English For Ethiopia",
        description: "Official Grade 9 English For Ethiopia student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "237 pages",
        size: "79 MB",
        image: "/books/covers/grade-9-english-for-ethiopia.png",
        pdf: "/books/pdfs/grade-9-english-for-ethiopia.pdf",
      },
      {
        name: "Geography",
        description: "Official Grade 9 Geography student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "237 pages",
        size: "20 MB",
        image: "/books/covers/grade-9-geography.png",
        pdf: "/books/pdfs/grade-9-geography.pdf",
      },
      {
        name: "Health and Physical Education (HPE)",
        description: "Official Grade 9 Health and Physical Education (HPE) student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "167 pages",
        size: "6 MB",
        image: "/books/covers/grade-9-health-and-physical-education-hpe.png",
        pdf: "/books/pdfs/grade-9-health-and-physical-education-hpe.pdf",
      },
      {
        name: "History",
        description: "Official Grade 9 History student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "219 pages",
        size: "9 MB",
        image: "/books/covers/grade-9-history.png",
        pdf: "/books/pdfs/grade-9-history.pdf",
      },
      {
        name: "Information Technology",
        description: "Official Grade 9 Information Technology student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "251 pages",
        size: "14 MB",
        image: "/books/covers/grade-9-information-technology.png",
        pdf: "/books/pdfs/grade-9-information-technology.pdf",
      },
      {
        name: "Mathematics",
        description: "Official Grade 9 Mathematics student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "375 pages",
        size: "18 MB",
        image: "/books/covers/grade-9-mathematics.png",
        pdf: "/books/pdfs/grade-9-mathematics.pdf",
      },
      {
        name: "Physics",
        description: "Official Grade 9 Physics student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "183 pages",
        size: "8 MB",
        image: "/books/covers/grade-9-physics.png",
        pdf: "/books/pdfs/grade-9-physics.pdf",
      },
    ],
  },
  {
    grade: 10,
    accent: "from-sky-500 to-cyan-500",
    description: "Grade 10 textbooks for stronger subject mastery and exam preparation.",
    subjects: [
      {
        name: "Amharic",
        description: "Official Grade 10 Amharic student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "164 pages",
        size: "4 MB",
        image: "/books/covers/grade-10-amharic.png",
        pdf: "/books/pdfs/grade-10-amharic.pdf",
      },
      {
        name: "Biology",
        description: "Official Grade 10 Biology student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "182 pages",
        size: "12 MB",
        image: "/books/covers/grade-10-biology.png",
        pdf: "/books/pdfs/grade-10-biology.pdf",
      },
      {
        name: "Chemistry",
        description: "Official Grade 10 Chemistry student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "306 pages",
        size: "6 MB",
        image: "/books/covers/grade-10-chemistry.png",
        pdf: "/books/pdfs/grade-10-chemistry.pdf",
      },
      {
        name: "Citizenship Education",
        description: "Official Grade 10 Citizenship Education student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "202 pages",
        size: "11 MB",
        image: "/books/covers/grade-10-citizenship-education.png",
        pdf: "/books/pdfs/grade-10-citizenship-education.pdf",
      },
      {
        name: "Economics",
        description: "Official Grade 10 Economics student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "190 pages",
        size: "3 MB",
        image: "/books/covers/grade-10-economics.png",
        pdf: "/books/pdfs/grade-10-economics.pdf",
      },
      {
        name: "English For Ethiopia",
        description: "Official Grade 10 English For Ethiopia student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "326 pages",
        size: "5 MB",
        image: "/books/covers/grade-10-english-for-ethiopia.png",
        pdf: "/books/pdfs/grade-10-english-for-ethiopia.pdf",
      },
      {
        name: "Geography",
        description: "Official Grade 10 Geography student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "214 pages",
        size: "11 MB",
        image: "/books/covers/grade-10-geography.png",
        pdf: "/books/pdfs/grade-10-geography.pdf",
      },
      {
        name: "Health and Physical Education (HPE)",
        description: "Official Grade 10 Health and Physical Education (HPE) student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "158 pages",
        size: "9 MB",
        image: "/books/covers/grade-10-health-and-physical-education-hpe.png",
        pdf: "/books/pdfs/grade-10-health-and-physical-education-hpe.pdf",
      },
      {
        name: "History",
        description: "Official Grade 10 History student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "246 pages",
        size: "10 MB",
        image: "/books/covers/grade-10-history.png",
        pdf: "/books/pdfs/grade-10-history.pdf",
      },
      {
        name: "Information Technology",
        description: "Official Grade 10 Information Technology student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "234 pages",
        size: "12 MB",
        image: "/books/covers/grade-10-information-technology.png",
        pdf: "/books/pdfs/grade-10-information-technology.pdf",
      },
      {
        name: "Mathematics",
        description: "Official Grade 10 Mathematics student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "394 pages",
        size: "17 MB",
        image: "/books/covers/grade-10-mathematics.png",
        pdf: "/books/pdfs/grade-10-mathematics.pdf",
      },
      {
        name: "Physics",
        description: "Official Grade 10 Physics student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "258 pages",
        size: "9 MB",
        image: "/books/covers/grade-10-physics.png",
        pdf: "/books/pdfs/grade-10-physics.pdf",
      },
    ],
  },
  {
    grade: 11,
    accent: "from-violet-500 to-fuchsia-500",
    description: "Upper-secondary textbooks for deeper science, social science, and language study.",
    subjects: [
      {
        name: "Agriculture",
        description: "Official Grade 11 Agriculture student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "270 pages",
        size: "20 MB",
        image: "/books/covers/grade-11-agriculture.png",
        pdf: "/books/pdfs/grade-11-agriculture.pdf",
      },
      {
        name: "Amharic",
        description: "Official Grade 11 Amharic student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "216 pages",
        size: "4 MB",
        image: "/books/covers/grade-11-amharic.png",
        pdf: "/books/pdfs/grade-11-amharic.pdf",
      },
      {
        name: "Biology",
        description: "Official Grade 11 Biology student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "294 pages",
        size: "38 MB",
        image: "/books/covers/grade-11-biology.png",
        pdf: "/books/pdfs/grade-11-biology.pdf",
      },
      {
        name: "Chemistry",
        description: "Official Grade 11 Chemistry student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "342 pages",
        size: "7 MB",
        image: "/books/covers/grade-11-chemistry.png",
        pdf: "/books/pdfs/grade-11-chemistry.pdf",
      },
      {
        name: "Economics",
        description: "Official Grade 11 Economics student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "202 pages",
        size: "5 MB",
        image: "/books/covers/grade-11-economics.png",
        pdf: "/books/pdfs/grade-11-economics.pdf",
      },
      {
        name: "English For Ethiopia",
        description: "Official Grade 11 English For Ethiopia student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "290 pages",
        size: "139 MB",
        image: "/books/covers/grade-11-english-for-ethiopia.png",
        pdf: "/books/pdfs/grade-11-english-for-ethiopia.pdf",
      },
      {
        name: "Geography",
        description: "Official Grade 11 Geography student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "254 pages",
        size: "11 MB",
        image: "/books/covers/grade-11-geography.png",
        pdf: "/books/pdfs/grade-11-geography.pdf",
      },
      {
        name: "History",
        description: "Official Grade 11 History student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "270 pages",
        size: "11 MB",
        image: "/books/covers/grade-11-history.png",
        pdf: "/books/pdfs/grade-11-history.pdf",
      },
      {
        name: "Information Technology",
        description: "Official Grade 11 Information Technology student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "170 pages",
        size: "4 MB",
        image: "/books/covers/grade-11-information-technology.png",
        pdf: "/books/pdfs/grade-11-information-technology.pdf",
      },
      {
        name: "Mathematics",
        description: "Official Grade 11 Mathematics student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "494 pages",
        size: "137 MB",
        image: "/books/covers/grade-11-mathematics.png",
        pdf: "/books/pdfs/grade-11-mathematics.pdf",
      },
      {
        name: "Physics",
        description: "Official Grade 11 Physics student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "338 pages",
        size: "9 MB",
        image: "/books/covers/grade-11-physics.png",
        pdf: "/books/pdfs/grade-11-physics.pdf",
      },
    ],
  },
  {
    grade: 12,
    accent: "from-amber-400 to-orange-500",
    description: "Final-year textbooks with local previews and direct downloads for revision.",
    subjects: [
      {
        name: "Agriculture",
        description: "Official Grade 12 Agriculture student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "302 pages",
        size: "38 MB",
        image: "/books/covers/grade-12-agriculure.png",
        pdf: "/books/pdfs/grade-12-agriculure.pdf",
      },
      {
        name: "Amharic",
        description: "Official Grade 12 Amharic student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "217 pages",
        size: "4 MB",
        image: "/books/covers/grade-12-amharic.png",
        pdf: "/books/pdfs/grade-12-amharic.pdf",
      },
      {
        name: "Biology",
        description: "Official Grade 12 Biology student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "358 pages",
        size: "172 MB",
        image: "/books/covers/grade-12-biology.png",
        pdf: "/books/pdfs/grade-12-biology.pdf",
      },
      {
        name: "Chemistry",
        description: "Official Grade 12 Chemistry student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "298 pages",
        size: "6 MB",
        image: "/books/covers/grade-12-chemistry.png",
        pdf: "/books/pdfs/grade-12-chemistry.pdf",
      },
      {
        name: "Economics",
        description: "Official Grade 12 Economics student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "214 pages",
        size: "4 MB",
        image: "/books/covers/grade-12-economics.png",
        pdf: "/books/pdfs/grade-12-economics.pdf",
      },
      {
        name: "English For Ethiopia",
        description: "Official Grade 12 English For Ethiopia student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "270 pages",
        size: "14 MB",
        image: "/books/covers/grade-12-english-for-ethiopia.png",
        pdf: "/books/pdfs/grade-12-english-for-ethiopia.pdf",
      },
      {
        name: "Geography",
        description: "Official Grade 12 Geography student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "266 pages",
        size: "11 MB",
        image: "/books/covers/grade-12-geography.png",
        pdf: "/books/pdfs/grade-12-geography.pdf",
      },
      {
        name: "History",
        description: "Official Grade 12 History student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "290 pages",
        size: "7 MB",
        image: "/books/covers/grade-12-history.png",
        pdf: "/books/pdfs/grade-12-history.pdf",
      },
      {
        name: "Information Technology",
        description: "Official Grade 12 Information Technology student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "210 pages",
        size: "9 MB",
        image: "/books/covers/grade-12-information-technology.png",
        pdf: "/books/pdfs/grade-12-information-technology.pdf",
      },
      {
        name: "Mathematics",
        description: "Official Grade 12 Mathematics student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "426 pages",
        size: "21 MB",
        image: "/books/covers/grade-12-mathematics.png",
        pdf: "/books/pdfs/grade-12-mathematics.pdf",
      },
      {
        name: "Physics",
        description: "Official Grade 12 Physics student textbook sourced from kehulum with local cover preview and PDF download.",
        pages: "186 pages",
        size: "11 MB",
        image: "/books/covers/grade-12-physics.png",
        pdf: "/books/pdfs/grade-12-physics.pdf",
      },
    ],
  },
];

export const getBooksGrade = (grade: number) =>
  booksByGrade.find((item) => item.grade === grade);
