import { MatricExamQuestion } from "./matricExams";

export const matric2015SocialHistoryQuestions: MatricExamQuestion[] = [
  {
    "id": "m2015-social-hist-1",
    "sectionDirection": "Choose the correct answer.",
    "question": "Which one of the following was a factor for the Oromo population movement of the 16 th century?",
    "options": [
      "The desire to expand Oromo religion",
      "The desire to find new pastures for cattle",
      "The need to expand the tax base of the Oromo",
      "The demand to establish political control over new areas"
    ],
    "correctAnswer": 1,
    "explanation": "The Oromo population movement in the 16th century was primarily driven by the need to find new pastures for their cattle, as they were pastoralist people. This is historically documented as the main push factor for their expansion."
  },
  {
    "id": "m2015-social-hist-2",
    "question": "What challenge did Emperor Serse Dingil face beyond the Mereb River in the 1570s?",
    "options": [
      "Turkish expansionism",
      "Disobedience from the na'ibs of Arkiko",
      "Mutiny among royal regiments in the province",
      "Rebellion by local people"
    ],
    "correctAnswer": 0,
    "explanation": "Emperor Serse Dingil faced Turkish expansionism beyond the Mereb River in the 1570s. The Ottoman Empire was expanding its influence in the Red Sea region during this period."
  },
  {
    "id": "m2015-social-hist-3",
    "question": "What achievements earned Iyasu I the nickname \"Iyasu the Great\"?",
    "options": [
      "The successful campaign against the Funj Sultanate in the west",
      "Revision of works related to the legal code and taxation",
      "Introduction of new forms of architecture in the city of Gondar",
      "Restoration of Gondernine rule over south-western Ethiopia"
    ],
    "correctAnswer": 3,
    "explanation": "Iyasu I earned the nickname 'Iyasu the Great' primarily for his restoration of Gondernine rule over south-western Ethiopia. He successfully campaigned to reassert imperial authority over lost territories."
  },
  {
    "id": "m2015-social-hist-4",
    "question": "What helped the Ching dynasty in China to gain the support of the indigenous Han ruling class?",
    "options": [
      "The continuation of Chinese administrative practices by the Ching",
      "The successful rejection of the \"Unequal Treaties\" by the Ching",
      "The reduction of the tax on the Chinese peasantry",
      "The opening of China for foreign trade and civilization by the Ching"
    ],
    "correctAnswer": 0,
    "explanation": "The Ching (Qing) dynasty gained support from the Han ruling class by continuing Chinese administrative practices. This policy of adopting Chinese institutions helped legitimize their rule."
  },
  {
    "id": "m2015-social-hist-5",
    "question": "What was the fundamental source of conflict between Charles I and the English Short Parliament?",
    "options": [
      "Disagreement on the authority of the king to sign treaties without consulting Parliament",
      "Dispute as to whether or not Presbyterians can be head of the English Church",
      "Disagreement on the nature of union between England and Scotland",
      "Dispute over raising taxes to suppress the rebellion in Scotland"
    ],
    "correctAnswer": 3,
    "explanation": "The fundamental source of conflict between Charles I and the English Short Parliament was the dispute over raising taxes to suppress the rebellion in Scotland. Parliament refused to grant funds without addressing grievances."
  },
  {
    "id": "m2015-social-hist-6",
    "question": "Which of the following is a dominant idea among Enlightenment thinkers?",
    "options": [
      "Man can attain salvation only through good work",
      "Humans can achieve progress through the application of reason",
      "Democracy is the best form of government",
      "Religion is important for social cohesion"
    ],
    "correctAnswer": 1,
    "explanation": "A dominant idea among Enlightenment thinkers was that humans can achieve progress through the application of reason. This belief in human rationality and progress was central to Enlightenment philosophy."
  },
  {
    "id": "m2015-social-hist-7",
    "question": "What was behind the outbreak of the Latin American revolutions in the early 19 th century?",
    "options": [
      "Implementation of the Monroe Doctrine by the US",
      "Re-division of Latin America between the Spanish and Portuguese",
      "Decline of French rule in the Atlantic colonies",
      "Ideas generated by the Enlightenment thinkers"
    ],
    "correctAnswer": 3,
    "explanation": "The Latin American revolutions in the early 19th century were inspired by ideas generated by Enlightenment thinkers, particularly concepts of liberty, equality, and popular sovereignty."
  },
  {
    "id": "m2015-social-hist-8",
    "question": "What was the common feature of the 1848 revolutions in Europe?",
    "options": [
      "They were inspired by the idea of establishing a liberal government",
      "They were primarily led by a coalition of youth groups and bourgeoisie",
      "They drew inspiration from the successful revolutions in America",
      "They ultimately failed because of divisions among the leadership on future goals"
    ],
    "correctAnswer": 3,
    "explanation": "The common feature of the 1848 revolutions in Europe was that they ultimately failed because of divisions among the leadership on future goals. Despite initial successes, internal disagreements led to their collapse."
  },
  {
    "id": "m2015-social-hist-9",
    "question": "Who was responsible for the end of the Funj Sultanate?",
    "options": [
      "The Abdallabi",
      "Iyasu II",
      "Amara Dunqas",
      "Mohammed Ali"
    ],
    "correctAnswer": 3,
    "explanation": "Mohammed Ali of Egypt was responsible for the end of the Funj Sultanate. He invaded and conquered the Funj kingdom in the 1820s, bringing it under Egyptian control."
  },
  {
    "id": "m2015-social-hist-10",
    "question": "Which one of the following explains Egypt's prosperity under the Mamluks?",
    "options": [
      "The successful participation of Egypt in the Crusades",
      "The decline of Ottoman control over the Mediterranean",
      "Egypt's participation in the trans-Saharan trade",
      "The construction of a canal across the Red Sea"
    ],
    "correctAnswer": 2,
    "explanation": "Egypt's prosperity under the Mamluks was largely due to Egypt's participation in the trans-Saharan trade. This trade brought wealth from West African gold and other commodities."
  },
  {
    "id": "m2015-social-hist-11",
    "question": "Which of the following people was responsible for invading India in the 14 th century?",
    "options": [
      "The Han",
      "The Arabs",
      "The Mongols",
      "The Huns"
    ],
    "correctAnswer": 2,
    "explanation": "The Mongols were responsible for invading India in the 14th century under Timur (Tamerlane) in 1398. This invasion had significant impact on the Delhi Sultanate."
  },
  {
    "id": "m2015-social-hist-12",
    "question": "Which one of the following is a Central Cushitic language?",
    "options": [
      "Gedeo",
      "Burji",
      "Beja",
      "Bilen"
    ],
    "correctAnswer": 3,
    "explanation": "Bilen is a Central Cushitic language. The other options (Gedeo, Burji, Beja) belong to different language families within the Cushitic or Afro-Asiatic groups."
  },
  {
    "id": "m2015-social-hist-13",
    "question": "Where was the ancient state of Punt located?",
    "options": [
      "The Eastern coast of the Red Sea",
      "In Northeast Africa",
      "On the Swahili Coast",
      "Along the Ethio-Sudan borderlands"
    ],
    "correctAnswer": 1,
    "explanation": "The ancient state of Punt was located in Northeast Africa, likely in the area of modern-day Somalia, Eritrea, or Sudan. It was a trading partner of ancient Egypt."
  },
  {
    "id": "m2015-social-hist-14",
    "question": "What factors facilitated the rise of the Zagwe Dynasty?",
    "options": [
      "The popularity that the Agaw gained because of the rock hewn churches",
      "The increased interaction of the Agaw elite with the Aksumite court",
      "The spread of Christianity among the Agaw populations",
      "The shift of the major trade routes from Massawa to Zeila"
    ],
    "correctAnswer": 0,
    "explanation": "The rise of the Zagwe Dynasty was facilitated by the popularity the Agaw gained because of the rock-hewn churches they built, particularly the famous churches of Lalibela."
  },
  {
    "id": "m2015-social-hist-15",
    "question": "Which of the following was characteristic of Renaissance Humanism?",
    "options": [
      "Desire to recreate the Roman Empire",
      "Study of classical Islamic literature",
      "Focus on how to achieve salvation",
      "Interest in everyday human conditions"
    ],
    "correctAnswer": 3,
    "explanation": "Renaissance Humanism was characterized by an interest in everyday human conditions and secular matters, moving away from the purely religious focus of the medieval period."
  },
  {
    "id": "m2015-social-hist-16",
    "question": "How did the Solomonic rulers of the medieval period in Ethiopia try to solve the problem of royal succession?",
    "options": [
      "By inventing a system of a caretaker administration that ruled for a few years until final selection of a king is made",
      "By designing a system in which the decisions of the Church leaders on succession became final",
      "By developing a prison system for male royal prison system in which male descendants of a monarch were kept",
      "By establishing a clear rule of succession"
    ],
    "correctAnswer": 2,
    "explanation": "The Solomonic rulers developed a prison system for male royal descendants, known as the 'mountain prisons,' to prevent succession disputes by isolating potential claimants."
  },
  {
    "id": "m2015-social-hist-17",
    "question": "Which one of the following was a characteristic feature of the Muslim sultanates of Medieval Ethiopia?",
    "options": [
      "Their economy was mainly dependent on trade",
      "Their rulers exercised limited power and authority",
      "Their populations were made up of Muslims and Christians",
      "Their ruling class were immigrants from Arabia"
    ],
    "correctAnswer": 0,
    "explanation": "A characteristic feature of the Muslim sultanates of Medieval Ethiopia was that their economy was mainly dependent on trade, particularly with the Red Sea and Indian Ocean trading networks."
  },
  {
    "id": "m2015-social-hist-18",
    "question": "Which one of the following is true about the Kingdom of Kafa?",
    "options": [
      "It was ruled by a king who had limited power",
      "It was created by invaders from neighbouring Enarya",
      "It had a dynasty that came from the Manjo clan",
      "It had developed an efficient system of defending its territory"
    ],
    "correctAnswer": 3,
    "explanation": "The Kingdom of Kafa had developed an efficient system of defending its territory through its well-organized military and natural defensive advantages."
  },
  {
    "id": "m2015-social-hist-19",
    "question": "What was the main cause for the expansion of the Christian kingdom during the medieval period?",
    "options": [
      "Determination to restore the lost territories of the Aksumites",
      "Ambition to acquire slaves for export to Arabia",
      "Desire to expand its resource base",
      "The need to expand Christianity"
    ],
    "correctAnswer": 2,
    "explanation": "The main cause for the expansion of the Christian kingdom during the medieval period was the desire to expand its resource base, including acquiring new lands and economic resources."
  },
  {
    "id": "m2015-social-hist-20",
    "question": "Which one of the following factors intensified the conflict between the Christian kingdom and the Sultanate of Adal in the 15 th and early 16 th centuries?",
    "options": [
      "The shift of the Christian political center to Shewa",
      "The introduction of new weapons like muskets",
      "The establishment of the Turks along the Red Sea coast",
      "The pressure created by the migration of lowland pastoralists"
    ],
    "correctAnswer": 2,
    "explanation": "The conflict between the Christian kingdom and the Sultanate of Adal intensified due to the establishment of the Turks along the Red Sea coast, which brought firearms and new military dynamics."
  },
  {
    "id": "m2015-social-hist-21",
    "question": "What was the factor that led to the decline of the gada institution among the Oromo of the Gibe region?",
    "options": [
      "Political influence of Sudanese states of the Ethio-Sudan border",
      "The shift of the economy from pastoralism to agriculture",
      "Warfare and the rise of powerful war leaders",
      "The conquest of the region by the forces of Menelik"
    ],
    "correctAnswer": 2,
    "explanation": "The gada institution declined among the Oromo of the Gibe region due to warfare and the rise of powerful war leaders, who established hereditary rule instead of the rotational gada system."
  },
  {
    "id": "m2015-social-hist-22",
    "question": "Which of the following is NOT a correct description of long-distance trade routes of 19 th century Ethiopia?",
    "options": [
      "Jiren-Rogge-Harar-Massawa",
      "Basso-Darita-Gonder-Metema",
      "Jiren-Seka-Soddo-Aliya Amba",
      "Bonga-Jiren-Asendabo-Darita"
    ],
    "correctAnswer": 2,
    "explanation": "The route Jiren-Seka-Soddo-Aliya Amba was not a correct description of 19th century Ethiopian long-distance trade routes. The other routes were historically documented."
  },
  {
    "id": "m2015-social-hist-23",
    "question": "What was Giuseppe Garibaldi's role in the unification of Italy?",
    "options": [
      "He brought together the Pope and Cavour to work for unification",
      "He inspired and led a popular uprising for Italian unification",
      "He secured Napoleon III's diplomatic support for Italian unification",
      "He deepened Italian national consciousness through his writings"
    ],
    "correctAnswer": 1,
    "explanation": "Giuseppe Garibaldi's role was to inspire and lead a popular uprising for Italian unification. He led the 'Expedition of the Thousand' that conquered the Kingdom of the Two Sicilies."
  },
  {
    "id": "m2015-social-hist-24",
    "question": "How did the Congress of Vienna of 1815 lay the ground for the German unification?",
    "options": [
      "It made Prussia the leading German state of the confederation",
      "It brought the different German states under one customs union",
      "It made German an official language for the confederation",
      "It created a German confederation led by Austria"
    ],
    "correctAnswer": 3,
    "explanation": "The Congress of Vienna created a German confederation led by Austria, which ultimately laid the groundwork for future German unification movements."
  },
  {
    "id": "m2015-social-hist-25",
    "question": "Which one of the following was a consequence of the American Civil War?",
    "options": [
      "Industrialization of American economy",
      "Colonization of the south by the north",
      "Toleration of slavery in some parts of the south",
      "End of racism across the whole of the United States"
    ],
    "correctAnswer": 0,
    "explanation": "A major consequence of the American Civil War was the industrialization of the American economy. The war accelerated Northern industrial growth and transformed the economic landscape."
  },
  {
    "id": "m2015-social-hist-26",
    "question": "Which of the following processes contributed to the emergence of the \"Eastern Question\"?",
    "options": [
      "The discovery of oil in territories ruled by the Ottoman Empire",
      "The rivalry between the Ottomans and Russians for control of the Mediterranean",
      "The spread of nationalism among the Slavic peoples of the Ottoman Empire",
      "The expansion of the Austrian Empire to lands that were previously under the control of the Ottomans"
    ],
    "correctAnswer": 2,
    "explanation": "The spread of nationalism among the Slavic peoples of the Ottoman Empire contributed to the emergence of the 'Eastern Question' - the problem of how to deal with the declining Ottoman Empire."
  },
  {
    "id": "m2015-social-hist-27",
    "question": "How did Tewodros II come to power?",
    "options": [
      "By defeating his opponents through military means",
      "By gaining the support of the Orthodox Church",
      "By claiming he was the Tewodros of The Fikaré Iyesus",
      "By using British diplomatic support"
    ],
    "correctAnswer": 0,
    "explanation": "Tewodros II came to power by defeating his opponents through military means. He rose through military campaigns against various regional lords and established his authority."
  },
  {
    "id": "m2015-social-hist-28",
    "question": "What was the significance of the Battle of Assam for Kassa Mircha of Tigray?",
    "options": [
      "It convinced the British to support him in his bid to become emperor",
      "It helped him defeat a major rival and hence become emperor",
      "It convinced him to modernize his army if he wanted to become emperor",
      "It helped him become the sole governor of the province of Tigray"
    ],
    "correctAnswer": 1,
    "explanation": "The Battle of Assam helped Kassa Mircha (later Emperor Yohannes IV) defeat a major rival and hence become emperor. This victory was a turning point in his rise to power."
  },
  {
    "id": "m2015-social-hist-29",
    "question": "What strategy did Menelik use in his expansion to the south prior to 1889?",
    "options": [
      "Overwhelming force across the whole region",
      "Force for state societies but negotiation among non-state peoples",
      "A combination of diplomacy and force across the whole region",
      "Peaceful methods among Christians but force in non-Christian areas"
    ],
    "correctAnswer": 1,
    "explanation": "Menelik used force for state societies but negotiation among non-state peoples. This differentiated approach allowed him to expand efficiently through different regions."
  },
  {
    "id": "m2015-social-hist-30",
    "question": "Why did Article 17 of the Wuchale Treaty become a source of conflict between Ethiopia and Italy?",
    "options": [
      "Because the Italian version stated that Ethiopia has agreed to become an Italian protectorate",
      "Because the Amharic and Italian versions did not agree on the boundaries of the two states",
      "Because the Italian version suggested that Menelik had agreed to give Mereb Melash to Italy",
      "Because the Amharic and Italian versions did not agree how long Italy should stay at Massawa"
    ],
    "correctAnswer": 0,
    "explanation": "Article 17 of the Wuchale Treaty became a source of conflict because the Italian version stated that Ethiopia had agreed to become an Italian protectorate, which was not in the Amharic version."
  },
  {
    "id": "m2015-social-hist-31",
    "question": "Which one of the following southern states exercised extensive influence in areas south of the Abbay before the 14 th century?",
    "options": [
      "Damot",
      "Bizamo",
      "Hadiya",
      "Enarea"
    ],
    "correctAnswer": 0,
    "explanation": "Damot was a southern state that exercised extensive influence in areas south of the Abbay before the 14th century. It was a significant pre-Aksumite and early medieval kingdom."
  },
  {
    "id": "m2015-social-hist-32",
    "question": "Which one of the following was a feature of European society during the \"Dark Ages\"?",
    "options": [
      "The movement of large number of people from the countryside to the cities",
      "The decline of Christianity and rise of traditional religious beliefs",
      "The rise in the power of local rulers at the expense of kings and emperors",
      "The shift of regional political power from Italy northwards to Scandinavia"
    ],
    "correctAnswer": 2,
    "explanation": "A feature of European society during the 'Dark Ages' was the rise in the power of local rulers at the expense of kings and emperors, leading to feudal fragmentation."
  },
  {
    "id": "m2015-social-hist-33",
    "question": "Which one of the following was a feature of early capitalism in Europe?",
    "options": [
      "The withdrawal of the special privileges granted to cities by rulers",
      "The growth of conflict between states and merchants over control of markets",
      "The shift of the economy from trading to banking and manufacturing",
      "The rise in importance of the bourgeoisie in economic and cultural life"
    ],
    "correctAnswer": 3,
    "explanation": "Early capitalism in Europe featured the rise in importance of the bourgeoisie in economic and cultural life, marking a shift from feudal aristocratic dominance."
  },
  {
    "id": "m2015-social-hist-34",
    "question": "What was the cause of the conflict between the Christian highland kingdom and the Muslim sultanates in the Medieval period?",
    "options": [
      "The desire of the ruling classes to collect war booty",
      "The determination by both parties to spread their religions",
      "The desire to control the lucrative Zeila trade route",
      "The need to control the salt producing regions of Afar"
    ],
    "correctAnswer": 2,
    "explanation": "The cause of conflict between the Christian highland kingdom and Muslim sultanates was the desire to control the lucrative Zeila trade route, which was economically vital for both."
  },
  {
    "id": "m2015-social-hist-35",
    "question": "Which one of the following was NOT a consequence of the Oromo population movement of the 16 th century?",
    "options": [
      "The adoption of aspects of the gada system by the Christian state",
      "The shift of some Oromo people to sedentary agriculture",
      "The assimilation of large number of groups by the Oromo",
      "The loss of territory by the Christian highland kingdom"
    ],
    "correctAnswer": 0,
    "explanation": "The adoption of aspects of the gada system by the Christian state was NOT a consequence of the Oromo movement. The other options (shift to agriculture, assimilation, loss of territory) were actual consequences."
  },
  {
    "id": "m2015-social-hist-36",
    "question": "Why did the Jesuits fail to keep Ethiopia a Catholic country during the reign of Susenyos? Because:",
    "options": [
      "they failed to bring in the military support they had promised to Susenyos",
      "their attempt led to widespread opposition by the population",
      "they sought to secure the support of the nobility for their cause",
      "they disagreed with Susenyos over the abolition of the tabot (Ark)"
    ],
    "correctAnswer": 1,
    "explanation": "The Jesuits failed because their attempt to convert Ethiopia to Catholicism led to widespread opposition by the population, resulting in revolt and the eventual abdication of Susenyos."
  },
  {
    "id": "m2015-social-hist-37",
    "question": "Which of the following southern African peoples were cattle herders?",
    "options": [
      "The Khoi",
      "The Hausa",
      "The Swahili",
      "The San"
    ],
    "correctAnswer": 0,
    "explanation": "The Khoi (Khoikhoi) were cattle herders in southern Africa, while the San were hunter-gatherers. The Hausa and Swahili were West and East African groups respectively."
  },
  {
    "id": "m2015-social-hist-38",
    "question": "Which one of the following was a term used for the second phase of the Trans-Atlantic slave trade?",
    "options": [
      "Legitimate slave trade",
      "Free Slave trade",
      "Pirratic Slave trade",
      "Monopolistic slave trade"
    ],
    "correctAnswer": 3,
    "explanation": "The second phase of the Trans-Atlantic slave trade was called 'Monopolistic slave trade' when European powers held official monopolies over the trade."
  },
  {
    "id": "m2015-social-hist-39",
    "question": "Which one of the following was a distinct feature of industrial capitalism in Europe in the 19 th century?",
    "options": [
      "The emergence of big share companies that traded all over the world",
      "The transformation of communication through advances in air and railway transportation",
      "The replacement of human and animal labor by new inanimate sources of power",
      "The shift of production from the factory to household workshops"
    ],
    "correctAnswer": 2,
    "explanation": "Industrial capitalism featured the replacement of human and animal labor by new inanimate sources of power, particularly steam power, which revolutionized production."
  },
  {
    "id": "m2015-social-hist-40",
    "question": "What was the fundamental cause of the American Civil War?",
    "options": [
      "The formation of closer relationship with the French by the colonists",
      "Attempts by the British to tighten control over the colonies",
      "Opposition by the colonies to British policy on slavery",
      "The unpopularity of George III in the colonies"
    ],
    "correctAnswer": 2,
    "explanation": "The fundamental cause of the American Civil War was opposition by the colonies to British policy on slavery, alongside economic and political tensions between North and South."
  },
  {
    "id": "m2015-social-hist-41",
    "question": "Which of the following is true about modernization in Ethiopia under Menelik II?",
    "options": [
      "It failed mainly for lack of finance",
      "It was not supported by large sections of the population",
      "It was advanced by the Cabinet established in 1907",
      "It was limited to the building of schools by foreign missionaries"
    ],
    "correctAnswer": 0,
    "explanation": "Modernization in Ethiopia under Menelik II failed mainly for lack of finance. The country lacked the resources needed for comprehensive modernization efforts."
  },
  {
    "id": "m2015-social-hist-42",
    "question": "What was the consequence of Bismarck's system of alliances for European politics?",
    "options": [
      "It helped Germany expand its influence in Europe as well as Asia",
      "It encouraged resort to diplomacy rather than war",
      "It established a balance of forces in Europe, thus averting war",
      "It led to the establishment of two hostile military camps in Europe"
    ],
    "correctAnswer": 3,
    "explanation": "Bismarck's system of alliances led to the establishment of two hostile military camps in Europe, which eventually contributed to the outbreak of World War I."
  },
  {
    "id": "m2015-social-hist-43",
    "question": "Which of the following was a consequence of the First World War?",
    "options": [
      "The establishment of British and French dominance in the Middle East",
      "The partition of Poland among the victorious powers",
      "The strengthening of the Austrian and Czarist empires",
      "The complete break-up of the German army and navy"
    ],
    "correctAnswer": 0,
    "explanation": "A consequence of the First World War was the establishment of British and French dominance in the Middle East through the mandate system created by the League of Nations."
  },
  {
    "id": "m2015-social-hist-44",
    "question": "Why did the Russian working class support the 1917 Revolution? Because:",
    "options": [
      "Conscription of workers had been introduced",
      "Living conditions of workers had worsened",
      "Many conscript workers had lost their lives",
      "the Czar had imposed a war tax on workers"
    ],
    "correctAnswer": 1,
    "explanation": "The Russian working class supported the 1917 Revolution because living conditions of workers had worsened significantly due to war-related economic disruptions."
  },
  {
    "id": "m2015-social-hist-45",
    "question": "What strategy did Italy use to undermine Ethiopian unity before the invasion of 1935?",
    "options": [
      "Preventing Ethiopia from producing arms locally",
      "Signing a treaty of peace and friendship with Ethiopia",
      "Bribing Ethiopian officials to weaken the imperial government",
      "Supporting Ethiopia's application to the League of Nations"
    ],
    "correctAnswer": 2,
    "explanation": "Italy undermined Ethiopian unity before the 1935 invasion by bribing Ethiopian officials to weaken the imperial government, using divide-and-conquer tactics."
  },
  {
    "id": "m2015-social-hist-46",
    "question": "Why was the Fascist rule limited largely to the urban centers during the period of Italian occupation of Ethiopia?",
    "options": [
      "the small Italian army could only control the towns",
      "the countryside was a base for the resistance",
      "urban services were concentrated in the towns",
      "Italian soldiers hated service in the countryside"
    ],
    "correctAnswer": 1,
    "explanation": "Fascist rule was limited largely to urban centers because the countryside was a base for the resistance movement, making rural areas difficult to control."
  },
  {
    "id": "m2015-social-hist-47",
    "question": "What was the fundamental factor for the outbreak of the Second World War?",
    "options": [
      "The spread of racism in Germany and Italy",
      "The arms race between the Triple Alliance and the Triple Entente",
      "The feeling of victimhood felt by Germans about the Versailles Treaty",
      "The policy of appeasement pursued by Britain and France"
    ],
    "correctAnswer": 2,
    "explanation": "The fundamental factor for WWII was the feeling of victimhood felt by Germans about the Versailles Treaty, which Hitler exploited to gain political support."
  },
  {
    "id": "m2015-social-hist-48",
    "question": "What was the immediate factor for the outbreak of the Second World War?",
    "options": [
      "The invasion of Manchuria by the Japanese",
      "The attack on Pearl Harbour by the Japanese",
      "The signing of the Nazi-Soviet non-aggression pact",
      "The invasion of Poland by the German army"
    ],
    "correctAnswer": 3,
    "explanation": "The immediate factor for WWII was the invasion of Poland by the German army on September 1, 1939, which led to Britain and France declaring war."
  },
  {
    "id": "m2015-social-hist-49",
    "question": "What was the importance of the Tehran Conference of 1943 in the formation of the United Nations?",
    "options": [
      "The Charter of the UN was signed by member states there",
      "The details of the UN structure were worked out there",
      "The idea of forming the UN received support from the great powers there",
      "The idea of creating the UN was first discussed there"
    ],
    "correctAnswer": 2,
    "explanation": "At the Tehran Conference of 1943, the idea of forming the UN received support from the great powers (Roosevelt, Churchill, and Stalin), paving the way for its creation."
  },
  {
    "id": "m2015-social-hist-50",
    "question": "Which of the following countries was a member of the Warsaw Pact?",
    "options": [
      "Hungary",
      "Turkey",
      "Greece",
      "Norway"
    ],
    "correctAnswer": 0,
    "explanation": "Hungary was a member of the Warsaw Pact, the Soviet-led military alliance in Eastern Europe established in 1955 as a counterbalance to NATO."
  },
  {
    "id": "m2015-social-hist-51",
    "question": "How does a historian establish the value of a source for his work?",
    "options": [
      "By carrying out a critical evaluation of the source he/she uses",
      "By making sure that the source comes from a national archive",
      "By checking it out against books written on a related subject",
      "By making sure that the source has been used by other historians"
    ],
    "correctAnswer": 0,
    "explanation": "A historian establishes the value of a source by carrying out a critical evaluation, assessing its authenticity, reliability, and relevance to the research question."
  },
  {
    "id": "m2015-social-hist-52",
    "question": "Which one of the following has been a limitation of Ethiopian historiography?",
    "options": [
      "Focus on the pre-modern period rather than the modern period",
      "Heavy dependence on oral sources rather than documents",
      "Heavy emphasis on political history than other kinds of history",
      "Focus on the history of the masses than elite members of society"
    ],
    "correctAnswer": 2,
    "explanation": "A limitation of Ethiopian historiography has been the heavy emphasis on political history rather than other kinds of history, such as social, economic, or cultural history."
  },
  {
    "id": "m2015-social-hist-53",
    "question": "What were the distinctive characteristics of Homo erectus?",
    "options": [
      "They migrated from Africa to other continents",
      "They were the first bipedal species of the genus Homo",
      "They first developed the technology of using fire",
      "They were the first tool making hominids"
    ],
    "correctAnswer": 2,
    "explanation": "Homo erectus is distinguished by being the first species to develop the technology of using fire, which was a major technological advancement in human evolution."
  },
  {
    "id": "m2015-social-hist-54",
    "question": "Which one of the following is correct about the Neolithic Revolution in the Ethiopian region?",
    "options": [
      "It had led to the development of language and ethnicity",
      "Its history has been reconstructed with artefacts from sites such as Gobedra and Lake Beseka",
      "It largely affected the northern parts of the region",
      "It started with the diffusion of different food crops from South Arabia"
    ],
    "correctAnswer": 1,
    "explanation": "The Neolithic Revolution in Ethiopia has been reconstructed with artefacts from sites such as Gobedra and Lake Beseka, which provide archaeological evidence of early agriculture."
  },
  {
    "id": "m2015-social-hist-55",
    "question": "What is the key idea of the theory of Oriental Despotism?",
    "options": [
      "That states emerged from the necessity of control over trade routes",
      "That states came into being as a result of war among despotic tribal leaders",
      "That states emerged out of the necessity of organizing irrigation works",
      "That early states were first emerged in the Orient"
    ],
    "correctAnswer": 2,
    "explanation": "The theory of Oriental Despotism proposes that states emerged out of the necessity of organizing large-scale irrigation works, requiring centralized authority."
  },
  {
    "id": "m2015-social-hist-56",
    "question": "Which one of the following is an achievement in Egypt during the New Kingdom?",
    "options": [
      "The unification of upper and lower Egypt",
      "The development of ideas about the afterlife",
      "The invention of the \"nomes\" as units of administration",
      "The expansion of the empire to parts of Asia and Africa"
    ],
    "correctAnswer": 3,
    "explanation": "During the New Kingdom, Egypt expanded its empire to parts of Asia and Africa, including Syria-Palestine and Nubia, making it a major imperial power."
  },
  {
    "id": "m2015-social-hist-57",
    "question": "Which one of the following is an achievement of Sumerian civilization?",
    "options": [
      "The invention a monotheistic religion",
      "The development of astronomy and mathematics",
      "The development of alphabetic writing",
      "The construction of great monuments for kings and gods"
    ],
    "correctAnswer": 1,
    "explanation": "The Sumerians developed astronomy and mathematics, including the base-60 number system we still use for time and angles today."
  },
  {
    "id": "m2015-social-hist-58",
    "question": "Which of the following is a characteristic feature of Athenian democracy?",
    "options": [
      "The dominance of the city by tyrants",
      "The prominence of the Senate in governing the city",
      "The passage of laws through direct participation of citizens",
      "The prominence of women in the making of laws"
    ],
    "correctAnswer": 2,
    "explanation": "Athenian democracy was characterized by the passage of laws through direct participation of citizens in the assembly, rather than through representatives."
  },
  {
    "id": "m2015-social-hist-59",
    "question": "What role did the Catholic Church play in Europe during the early Middle Ages?",
    "options": [
      "As a home for the development of democratic ideas",
      "As a supporter of capitalistic enterprises",
      "As a protector of the rights of peasants and serfs",
      "As a center of culture and learning"
    ],
    "correctAnswer": 3,
    "explanation": "During the early Middle Ages, the Catholic Church served as a center of culture and learning, preserving knowledge and providing education in monasteries and cathedral schools."
  },
  {
    "id": "m2015-social-hist-60",
    "question": "What was the battle that led to the end of Persian Empire in the 7th century?",
    "options": [
      "The Battle of Karbala",
      "The Battle Nihawand",
      "The Battle of Tours",
      "The Battle of Qadesiyya"
    ],
    "correctAnswer": 1,
    "explanation": "The Battle of Nihawand (642 CE) led to the end of the Persian Empire, marking the decisive victory of Muslim Arab forces over the Sassanid Persians."
  },
  {
    "id": "m2015-social-hist-61",
    "question": "Which of the following helped Italy achieve unification in the 19th century?",
    "options": [
      "The adoption of a policy of neutrality by Cavour in the Crimean War",
      "The weakening of the power of the Pope in Europe",
      "The spread of Italian nationalism in the Peninsula",
      "The support of France and Austria to the Italian cause"
    ],
    "correctAnswer": 2,
    "explanation": "Italy achieved unification in the 19th century through the spread of Italian nationalism throughout the Italian Peninsula, led by figures like Mazzini, Cavour, and Garibaldi."
  },
  {
    "id": "m2015-social-hist-62",
    "question": "In what ways did the British and French systems of administration in colonial Africa differ?",
    "options": [
      "The British used private companies in administering their colonies while the French did not use such companies",
      "The British sought to make Africans full citizens while the French denied citizenship to Africans",
      "The British used excessive force in their colonies while the French rarely resorted to violence",
      "The British ruled indirectly through local chiefs while the French ruled directly themselves"
    ],
    "correctAnswer": 3,
    "explanation": "The British used indirect rule through local chiefs while the French ruled directly themselves through appointed administrators, representing different colonial administrative philosophies."
  },
  {
    "id": "m2015-social-hist-63",
    "question": "How did long distance trade help in the consolidation of states in the Gibe region?",
    "options": [
      "By introducing the idea of kingship from the Christian kingdom",
      "By bringing messages of encouragement from elsewhere rulers",
      "Through the introduction of modern firearms that helped rulers defeat rivals",
      "By introducing new ideas and practices that legitimized the power of rulers"
    ],
    "correctAnswer": 3,
    "explanation": "Long distance trade helped consolidate states in the Gibe region by introducing new ideas and practices that legitimized the power of rulers and connected them to wider networks."
  },
  {
    "id": "m2015-social-hist-64",
    "question": "What was the major difference between the administrative styles of emperors Tewodros and Yohannes?",
    "options": [
      "Tewodros sought to use the Church in his administration while Yohannes did not",
      "Tewodros centralized power in his hands while Yohannes did not",
      "Tewodros employed Europeans in his administration while Yohannes did not",
      "Tewdros sought to use modern techniques of administration while Yohannes did not"
    ],
    "correctAnswer": 1,
    "explanation": "The major difference between Tewodros and Yohannes was that Tewodros centralized power in his hands while Yohannes did not achieve the same level of centralization."
  },
  {
    "id": "m2015-social-hist-65",
    "question": "What was the tactic used by the Ethiopians to eject the Italians out of Mekelle in January 1896?",
    "options": [
      "Misleading them through false movements of troops",
      "Spreading propaganda against their Eritrean askaris",
      "Cutting rebellion against them in Eritrea",
      "Denying them access to sources of water"
    ],
    "correctAnswer": 3,
    "explanation": "The Ethiopians used the tactic of denying the Italians access to sources of water to eject them from Mekelle in January 1896, forcing their surrender."
  },
  {
    "id": "m2015-social-hist-66",
    "question": "Why did the Shewan nobility oppose Lij Iyasu?",
    "options": [
      "he threatened the Orthodox Church by converting to Islam",
      "he threatened their political position in the Empire",
      "he worked to reorganize Ethiopia's foreign policy",
      "he sought to introduce a modern system of administration"
    ],
    "correctAnswer": 1,
    "explanation": "The Shewan nobility opposed Lij Iyasu because he threatened their political position in the Empire, fearing loss of their traditional privileges and influence."
  },
  {
    "id": "m2015-social-hist-67",
    "question": "Which one of the following initiatives of Lij Iyasu was important in reforming the legal system in the country?",
    "options": [
      "Establishment of an audit department in the Ministry of Finance",
      "Introduction of the German legal code to the country",
      "Introduction of a new way of assessing tax on produce",
      "Abolition of the system of identifying robbers and thieves"
    ],
    "correctAnswer": 3,
    "explanation": "Lij Iyasu's initiative to abolish the system of identifying robbers and thieves was important in reforming the legal system, moving toward more modern judicial practices."
  },
  {
    "id": "m2015-social-hist-68",
    "question": "What was the main feature of the Diarchy in the government of early 20th-century Ethiopia?",
    "options": [
      "Rivalry between conservative and progressive groups in the ruling class",
      "Less rivalry among the nobility compared to the preceding period",
      "Rapid penetration of European institutions of government",
      "Consolidation of power by the Empress at the expense of the Regent"
    ],
    "correctAnswer": 0,
    "explanation": "The main feature of the Diarchy in early 20th-century Ethiopia was rivalry between conservative and progressive groups in the ruling class, particularly between the Empress and the Regent."
  },
  {
    "id": "m2015-social-hist-69",
    "question": "Which one of the following provisions of the 1931 Constitution enabled the creation of autocratic rule by Emperor Haile Sellassie? The provision which:",
    "options": [
      "stated that the Emperor should be the direct of descendant of King Solomon",
      "granted the Emperor the right to sign treaties with foreign powers",
      "gave the Emperor the right to disband parliament at his own will",
      "stated the parliament should have lower and upper chambers"
    ],
    "correctAnswer": 2,
    "explanation": "The 1931 Constitution enabled autocratic rule by granting the Emperor the right to disband parliament at his own will, centralizing power in the monarch."
  },
  {
    "id": "m2015-social-hist-70",
    "question": "Why did the Ashanti Empire succeed in repulsing the British in 1876?",
    "options": [
      "they had witches who terrorized the British",
      "they formed an alliance with the coastal Fante people",
      "the British had support from the French",
      "they had a well-organized army"
    ],
    "correctAnswer": 3,
    "explanation": "The Ashanti Empire succeeded in repulsing the British in 1876 because they had a well-organized army with effective military leadership and strategies."
  },
  {
    "id": "m2015-social-hist-71",
    "question": "What strategy did the Indian National Congress adopt in fighting for independence?",
    "options": [
      "Working with the Japanese to undermine the British",
      "Forming a united front with the Muslim League",
      "Armed struggle and civil disobedience methods",
      "Non-violence struggle methods"
    ],
    "correctAnswer": 3,
    "explanation": "The Indian National Congress adopted non-violence struggle methods under Gandhi's leadership, using civil disobedience and peaceful resistance against British rule."
  },
  {
    "id": "m2015-social-hist-72",
    "question": "Which one of the following was a consequence of the First Arab-Israeli War?",
    "options": [
      "The conquest of the whole of Jerusalem by Israel",
      "The formation of the PLO as leader of the Palestinians",
      "The emergence of a Palestinian Arab refugee problem",
      "The recognition of Israel as an independent state"
    ],
    "correctAnswer": 2,
    "explanation": "A consequence of the First Arab-Israeli War was the emergence of a Palestinian Arab refugee problem, as hundreds of thousands of Palestinians fled or were expelled."
  },
  {
    "id": "m2015-social-hist-73",
    "question": "Why did the USA decide to intervene in Vietnam after the French defeat?",
    "options": [
      "Promise given to France that it its defeat by the Vietnamese forces would be avenged",
      "Dislike for the idea of partition of Vietnam between the north and south",
      "To test the extent to which Russia was determined to maintain its dominance in Asia",
      "Fear that Vietnamese victory would lead to the spread of communism across the region"
    ],
    "correctAnswer": 3,
    "explanation": "The USA intervened in Vietnam after the French defeat because of fear that Vietnamese victory would lead to the spread of communism across the region (the domino theory)."
  },
  {
    "id": "m2015-social-hist-74",
    "question": "How did the British help Haile Selassie consolidate his powers after 1941?",
    "options": [
      "By keeping the Italian's out of all Somali-inhabited areas",
      "By training and equipping his army",
      "By keeping control over Ethiopia's foreign relations",
      "By restoring his government in troublesome provinces like the Ogaden"
    ],
    "correctAnswer": 1,
    "explanation": "The British helped Haile Selassie consolidate his powers after 1941 by training and equipping his army, which strengthened his control over the country."
  },
  {
    "id": "m2015-social-hist-75",
    "question": "Which one of the following became elective under the 1955 Constitution?",
    "options": [
      "The Crown Council",
      "The Office of the Prime Minister",
      "The Senate",
      "The Chamber of Deputies"
    ],
    "correctAnswer": 3,
    "explanation": "The Chamber of Deputies became elective under the 1955 Constitution, representing a step toward constitutional monarchy and parliamentary representation."
  },
  {
    "id": "m2015-social-hist-76",
    "question": "Why did the 1960 coup against Haile Sellassie fail?",
    "options": [
      "the neighbouring colonial powers opposed it",
      "it was not planned and led effectively",
      "the people of Addis Ababa did not support it",
      "it was led by a civilian with no military experience"
    ],
    "correctAnswer": 1,
    "explanation": "The 1960 coup against Haile Selassie failed because it was not planned and led effectively, lacking proper coordination and popular support."
  },
  {
    "id": "m2015-social-hist-77",
    "question": "Which one of the following was a consequence of the 1974 Ethiopian Revolution?",
    "options": [
      "Abolition of status and class",
      "Transformation of peasant agriculture",
      "Centralization of power under a new regime",
      "Democratization of state and politics"
    ],
    "correctAnswer": 2,
    "explanation": "A consequence of the 1974 Ethiopian Revolution was the centralization of power under a new regime (the Derg), which overthrew the imperial system."
  },
  {
    "id": "m2015-social-hist-78",
    "question": "What was the distinctive feature of the pan-African movement as practiced by Garvey?",
    "options": [
      "That blacks in the diaspora can achieve full independence only by returning to Africa",
      "That the Pan-African movement should be led by Africans in the Continent",
      "That 'pan-Africanism' should ensure economic independence for Africans",
      "That blacks should fight for their rights in their respective countries"
    ],
    "correctAnswer": 0,
    "explanation": "Marcus Garvey's pan-African movement advocated that blacks in the diaspora could achieve full independence only by returning to Africa, promoting the 'Back to Africa' movement."
  },
  {
    "id": "m2015-social-hist-79",
    "question": "What strategy was used by the Mau Mau in struggling for Kenya's independence?",
    "options": [
      "Putting diplomatic pressure on the British at the UN",
      "Organizing an armed struggle against the British",
      "Adopting the principle of non-violent struggle used in India",
      "Frighten out the British by undertaking scary oaths"
    ],
    "correctAnswer": 1,
    "explanation": "The Mau Mau organized an armed struggle against the British in Kenya, using guerrilla warfare tactics to fight for land and independence."
  },
  {
    "id": "m2015-social-hist-80",
    "question": "What was the idea articulated at the All-African People's Conference at Accra that became a key principle of the OAU? The idea that:",
    "options": [
      "all African states should work towards democratizing the state",
      "African states should stand with oppressed nations globally",
      "the immediate goal of Africans should be economic union",
      "states should respect each other's territorial integrity"
    ],
    "correctAnswer": 3,
    "explanation": "The All-African People's Conference at Accra established the principle that African states should respect each other's territorial integrity, a key OAU principle."
  },
  {
    "id": "m2015-social-hist-81",
    "question": "What is prehistory?",
    "options": [
      "The method palaeontologists' use in dating fossils",
      "The method archaeologists use to dig out material objects",
      "The study of the period before the beginning of writing",
      "The study of non-literate societies"
    ],
    "correctAnswer": 2,
    "explanation": "Prehistory is the study of the period before the beginning of writing, encompassing all human history before written records were kept."
  },
  {
    "id": "m2015-social-hist-82",
    "question": "Which of the following is correct about the theory of evolution?",
    "options": [
      "Claims that human beings first originated in Europe",
      "States that humans are products of natural selection and adaptation",
      "Argues that humans were first civilized in ancient Greece and Rome",
      "Argues that human beings are descendants of Adam and Eve"
    ],
    "correctAnswer": 1,
    "explanation": "The theory of evolution states that humans are products of natural selection and adaptation, as proposed by Charles Darwin."
  },
  {
    "id": "m2015-social-hist-83",
    "question": "Which of the following is correct about the Mesolithic age?",
    "options": [
      "It is the longest of the three stone ages in human prehistory",
      "It witnessed the shift from hunting and gathering to agriculture",
      "It was a period that preceded the Neolithic age",
      "Its defining feature was the invention of the technology of fire"
    ],
    "correctAnswer": 1,
    "explanation": "The Mesolithic age witnessed the shift from hunting and gathering to agriculture, serving as a transitional period between the Paleolithic and Neolithic ages."
  },
  {
    "id": "m2015-social-hist-84",
    "question": "What is the central point in the theocratic theory of state formation?",
    "options": [
      "That states emerged first in The Middle East",
      "That states were created by religious experts",
      "states were formed along river valleys",
      "It emerged with the emergence of private property"
    ],
    "correctAnswer": 1,
    "explanation": "The central point of the theocratic theory of state formation is that states were created by religious experts or through religious authority."
  },
  {
    "id": "m2015-social-hist-85",
    "question": "What does the construction of the pyramids by the ancient Egyptians demonstrate?",
    "options": [
      "They had made significant advances in engineering and architecture",
      "They believed in the idea of life after death",
      "They had intense interaction with Sumer",
      "Their rulers mobilized vast resources from subject populations"
    ],
    "correctAnswer": 0,
    "explanation": "The construction of the pyramids demonstrates that the ancient Egyptians had made significant advances in engineering and architecture, requiring sophisticated mathematical knowledge."
  },
  {
    "id": "m2015-social-hist-86",
    "question": "Which of the following achievements of ancient Persia helped the state in maintaining administrative control of the Empire?",
    "options": [
      "The construction of a defensive wall along the borders of the Empire",
      "Effective use of examinations to recruit administrators",
      "The introduction of an effective postal relay system",
      "The development of a religion called Zoroastrianism"
    ],
    "correctAnswer": 2,
    "explanation": "Ancient Persia maintained administrative control through the introduction of an effective postal relay system, known as the Angarium, which facilitated rapid communication."
  },
  {
    "id": "m2015-social-hist-87",
    "question": "Which one of the following was the earliest state in Ethiopia and the Horn?",
    "options": [
      "Aksum",
      "Damat",
      "Yeba",
      "Punt"
    ],
    "correctAnswer": 3,
    "explanation": "Punt was the earliest state in Ethiopia and the Horn, existing as a trading partner with ancient Egypt from at least the 3rd millennium BCE."
  },
  {
    "id": "m2015-social-hist-88",
    "question": "Which one of the following is a major achievement of the Muslim Arab civilization?",
    "options": [
      "The opening up of new trade routes to Africa and Asia",
      "The preservation of ancient Greek texts through translation",
      "The development of paper money for international trade",
      "The introduction of new technologies of warfare to Europe"
    ],
    "correctAnswer": 1,
    "explanation": "A major achievement of Muslim Arab civilization was the preservation of ancient Greek texts through translation, which were later reintroduced to Europe."
  },
  {
    "id": "m2015-social-hist-89",
    "question": "What features of the Zagwe period show that there was cultural continuity with the Aksumite period?",
    "options": [
      "The use of Greek as a commercial language",
      "The attempt by the state to expand its territory to the eastern lowlands",
      "The important role Christianity enjoyed as official religion of the state",
      "The continued importance of Debre Masawa and Zeyla for international trade"
    ],
    "correctAnswer": 2,
    "explanation": "Cultural continuity between the Zagwe and Aksumite periods is shown by the important role Christianity enjoyed as the official religion of the state."
  },
  {
    "id": "m2015-social-hist-90",
    "question": "Why did the Christian highland kingdom in Medieval Ethiopia depend on mobile camps rather than permanent capitals?",
    "options": [
      "there was scarcity of lime (nora) which was important for building permanent buildings",
      "the mobile camps enabled rulers to control their empire more effectively than the permanent capitals",
      "the warrior kings of the time disliked the luxury life associated with permanent towns",
      "the tradition of building towns had disappeared with the Aksumites"
    ],
    "correctAnswer": 1,
    "explanation": "The Christian highland kingdom depended on mobile camps because they enabled rulers to control their empire more effectively than permanent capitals, allowing rapid response to threats."
  },
  {
    "id": "m2015-social-hist-91",
    "question": "Which one of the following was a major cause of The First World War?",
    "options": [
      "Rise of Intense nationalism among European countries",
      "Contest over who should control the oil fields of the Middle East",
      "Disagreement among European powers on the partition of Africa",
      "Rivalry over spheres of influence in Southeast Asia"
    ],
    "correctAnswer": 0,
    "explanation": "A major cause of World War I was the rise of intense nationalism among European countries, which created tensions and rivalries between the great powers."
  },
  {
    "id": "m2015-social-hist-92",
    "question": "Which one of the following was responsible for the outbreak of the 1917 Russian Revolution?",
    "options": [
      "The imposition of a harsh treaty by Germany over Russia",
      "The dismissal of the Duma by Czar Nicholas II",
      "The military losses that Russia suffered in WWI",
      "The assassination of Rasputin by the socialists"
    ],
    "correctAnswer": 2,
    "explanation": "The military losses that Russia suffered in WWI were responsible for the outbreak of the 1917 Russian Revolution, as they discredited the Tsarist regime."
  },
  {
    "id": "m2015-social-hist-93",
    "question": "Which one of the following was true about the period of Italian occupation of Ethiopia?",
    "options": [
      "The expansion of road infrastructure",
      "The creation of an educated class",
      "The growth of heavy industries",
      "The introduction of decentralized administration"
    ],
    "correctAnswer": 0,
    "explanation": "During the Italian occupation, there was expansion of road infrastructure as the Italians built roads to facilitate military control and economic exploitation."
  },
  {
    "id": "m2015-social-hist-94",
    "question": "How did the outbreak of WWII in Europe affect Ethiopia?",
    "options": [
      "It led the British to focus on Europe and hence delayed Ethiopia's liberation",
      "It led to the reduction of Italian troops in Ethiopia and hence encouraged the growth of the resistance movement",
      "It forced the Ethiopian resistance movement to change its tactics from guerrilla warfare to conventional warfare",
      "It gained Ethiopia the support of the British government and hence facilitated its liberation"
    ],
    "correctAnswer": 1,
    "explanation": "WWII led to the reduction of Italian troops in Ethiopia, which encouraged the growth of the resistance movement (the Patriots/Arbegnoch)."
  },
  {
    "id": "m2015-social-hist-95",
    "question": "Why was the UNO established?",
    "options": [
      "To provide a way out of Cold War politics",
      "To facilitate the process of decolonization",
      "To resolve international conflicts peacefully",
      "To fight against global climate change"
    ],
    "correctAnswer": 2,
    "explanation": "The UNO was established to resolve international conflicts peacefully, following the failure of the League of Nations to prevent World War II."
  },
  {
    "id": "m2015-social-hist-96",
    "question": "What did the anti-colonial movements in Algeria and Kenya in the 1950s have in common?",
    "options": [
      "Both initially opposed complete independence but accepted it later",
      "Both tried peaceful methods but resorted to armed resistance when that failed",
      "Both were led by leaders who supported the Indian tactic of peaceful resistance",
      "Both were urban based movements that sought to advance the interests of the middle classes"
    ],
    "correctAnswer": 1,
    "explanation": "The anti-colonial movements in Algeria and Kenya both tried peaceful methods but resorted to armed resistance when peaceful approaches failed to achieve independence."
  },
  {
    "id": "m2015-social-hist-97",
    "question": "Why did independent African states establish the OAU in 1963?",
    "options": [
      "Because the United States had encouraged them to do so",
      "Because they desired to spread democracy across the Continent",
      "Because they wanted to establish an association independent of the Super Powers",
      "Because they wanted to advance the struggle against colonialism"
    ],
    "correctAnswer": 2,
    "explanation": "Independent African states established the OAU in 1963 because they wanted to establish an association independent of the Super Powers, promoting African unity and cooperation."
  },
  {
    "id": "m2015-social-hist-98",
    "question": "Which one of the following institutions in Ethiopia was rebuilt with the help of the US in the post-liberation period?",
    "options": [
      "The Imperial Highway Authority",
      "The Parliament",
      "The Imperial Board of Telecommunications",
      "The Imperial Body Guard"
    ],
    "correctAnswer": 2,
    "explanation": "The Imperial Board of Telecommunications was rebuilt with US help in the post-liberation period, as part of modernization efforts supported by American aid."
  },
  {
    "id": "m2015-social-hist-99",
    "question": "Which one of the following was a consequence of the 1973-74 famine for the Imperial Government of Ethiopia?",
    "options": [
      "The inability of the government to repulse the Somali invasion",
      "The withdrawal of US support from the government",
      "The adoption of a radical land reform program",
      "The loss of legitimacy for the regime"
    ],
    "correctAnswer": 3,
    "explanation": "The 1973-74 famine led to the loss of legitimacy for the Imperial Government, as it demonstrated the government's inability to address the suffering of its people."
  },
  {
    "id": "m2015-social-hist-100",
    "question": "Which one of the following was responsible for unpopularity of the Derg Regime?",
    "options": [
      "Formation of an alliance with Socialist Cuba",
      "The passage of the land reform proclamation",
      "Using violence against opposition groups",
      "Organizing the Idget Behireti campaign"
    ],
    "correctAnswer": 2,
    "explanation": "The Derg Regime became unpopular because of using violence against opposition groups, including the Red Terror campaign that targeted political opponents."
  }
];
